Add global fragment support to schemas
smartprix/gqutils pull request #19
Opened 2019-06-14 10:11 UTC by rohit-smpx

Closes #17 

- Also fixes a bug where interfaces were being mutated (25c7ccd)
- Move `schemaName` option from `exec` to constructor because fragments are bound to schemas

2019-06-17 06:51 UTC, ajeet-smpx requested changes

2019-06-17 06:51 UTC, ajeet-smpx commented on src/Gql.js
> +		if (!this._fragments || this._fragments[name] === undefined) throw new Error(`[schema:${this._schemaName}] Invalid fragment name, ${name}`);
Can throw error like `Method not allowed` if `Gql` is constructed with `api` option.

2019-06-17 06:51 UTC, ajeet-smpx commented on src/Gql.js
>  		let response = Connect
`requestOptions = _.defaults(requestOptions, this._api)` ?

2019-06-17 06:51 UTC, ajeet-smpx commented on index.d.ts
> +		 * **NOTE:** Works only if if schema config options are passed
typo: `if if`

2019-06-17 06:51 UTC, ajeet-smpx commented on src/Schema.js
> +				if (_.isPlainObject(field.args)) str += convertObjToGqlArg(field.args);
can use `Gql.toGqlArg(field.args, {roundBrackets: true})`

2019-06-17 07:35 UTC, rohit-smpx commented on src/Schema.js
> +				if (_.isPlainObject(field.args)) str += convertObjToGqlArg(field.args);
was casing circular dependency

2019-06-17 08:04 UTC, rohit-smpx commented on src/Gql.js
>  		let response = Connect
Added those to Connect before requestOptions and let connect handle merging them.

2019-06-20 09:04 UTC, hit12369 commented
README needs to be updated about use of `fragments`.

2019-06-20 11:35 UTC, rohit-smpx commented
> README needs to be updated about use of `fragments`.

Done

2019-06-20 11:44 UTC, merged