Merge fields with interface while parsing args too
smartprix/gqutils pull request #21
Opened 2019-06-21 09:33 UTC by rohit-smpx

Interface fields were not being considered in `$default` in args

2019-07-03 05:49 UTC, rohit-smpx commented
@hit12369

2019-07-04 10:49 UTC, ajeet-smpx requested changes

2019-07-04 10:49 UTC, ajeet-smpx commented on src/Gql.js
> +	args(arg, {pick} = {}) {
Method name should be `arg` as defined in typescript. And it does not handle array type `opts`.

2019-07-04 10:49 UTC, ajeet-smpx commented on src/index.js
> +	const getTypeStringForFragments = ({fragments, enums}, schemaName) => `\
better variable name: getTypeStringForFragmentsAndEnums ?

2019-07-04 10:49 UTC, ajeet-smpx commented on src/index.js
> +			${Object.keys(fragments).map(key => `${key}: GqlFragment;`).join('\n\t\t\t')}
can use `name` instead of `key` for better readability

2019-07-04 13:00 UTC, ajeet-smpx requested changes

2019-07-04 13:00 UTC, ajeet-smpx commented on src/Gql.js
> +	arg(arg, opts = []) {
default empty array will pick nothing from `arg`. Can check for empty array in `toGqlArg` or remove default value.

2019-07-04 13:01 UTC, rohit-smpx commented on src/Gql.js
> +	arg(arg, opts = []) {
Oops

2019-07-04 13:26 UTC, ajeet-smpx approved these changes

2019-07-09 08:32 UTC, merged