Gql Base Class
smartprix/gqutils pull request #28
Opened 2019-08-06 10:31 UTC by ajeet-smpx

Split `Gql` into `Gql` (Base), `GqlApi` (Derived) & `GqlSchema` (Derived)

2019-08-07 08:05 UTC, rohit-gohri requested changes
Add section in Readme on how to use just the GqlApi class without importing from index and use in client side.

2019-08-07 08:05 UTC, rohit-gohri commented on index.d.ts
> +		requestOptions?: Pick<RequestOptions, 'headers' | 'cookies'>;
allow any other key too (`...other`)

2019-08-07 08:05 UTC, rohit-gohri commented on index.d.ts
> +	class GqlApi<FragmentsMap = gqlFragmentMap, EnumsMap = gqlEnumMap> extends Gql<gqlFragmentMap, gqlEnumMap> {
Types passed should not be default but the input
```suggestion
	class GqlApi<FragmentsMap = gqlFragmentMap, EnumsMap = gqlEnumMap> extends Gql<FragmentsMap, EnumsMap> {
```

2019-08-07 08:05 UTC, rohit-gohri commented on index.d.ts
> +	class GqlSchema<FragmentsMap = gqlFragmentMap, EnumsMap = gqlEnumMap> extends Gql<gqlFragmentMap, gqlEnumMap> {
Types passed should not be default but the input
```suggestion
	class GqlSchema<FragmentsMap = gqlFragmentMap, EnumsMap = gqlEnumMap> extends Gql<FragmentsMap, EnumsMap> {
```

2019-08-07 08:05 UTC, rohit-gohri commented on index.d.ts
> +		static postRequest(url: string, opts: {body: any} & Omit<RequestOptions, 'endpoint'>): Promise<response>;
Allow other?

2019-08-07 08:05 UTC, rohit-gohri commented on index.d.ts
> +		static postRequest(url: string, opts: {body: any} & Omit<RequestOptions, 'endpoint'>): Promise<response>;
return value is actually data and not response anymore

2019-08-07 08:05 UTC, rohit-smpx commented on src/Gql.js
> +class GqlApiError extends Error {}
Error classes can be moved to GqlApi and GqlSchema itself?

2019-08-07 08:05 UTC, rohit-smpx commented on src/index.js
> +async function postRequest(url, {headers, cookies, body, token} = {}) {
move to separate (`defaultPostRequest`) file and import from there.

2019-08-07 08:05 UTC, rohit-smpx commented on src/index.js
> +	const response = require('sm-utils').Connect
Remove global require, no longer needed

2019-08-07 08:06 UTC, rohit-smpx commented on src/Gql.js
> +		const result = await this._getQueryResult(query, {context, variables, requestOptions});
add this to types too? as an abstract function

2019-08-09 06:07 UTC, rohit-gohri approved these changes

2019-08-14 09:03 UTC, hit12369 commented
Is this meant to be used from the frontend? It isn't mentioned what to import. I guess package.json would need to be changed too.

2019-08-14 09:07 UTC, rohit-smpx commented
> Is this meant to be used from the frontend? It isn't mentioned what to import. I guess package.json would need to be changed too.

It is meant for clients. Can be used from frontend too though. A `broswer` field in package.json?

2019-08-14 09:10 UTC, hit12369 commented
> > Is this meant to be used from the frontend? It isn't mentioned what to import. I guess package.json would need to be changed too.
> 
> It is meant for clients. Can be used from frontend too though. A `broswer` field in package.json?
> 
> There is an example in Readme

Yes, a browser field. Readme doesn't specify how to import the class. Also a sample implementation with `fetch` would be nice (don't import by default, also mention in readme).

2019-08-14 11:40 UTC, rohit-smpx commented
> Yes, a browser field. Readme doesn't specify how to import the class. Also a sample implementation with `fetch` would be nice (don't import by default, also mention in readme).


Done

2019-08-19 07:45 UTC, merged